---
version: 2.1

jobs:
  test:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: print HelloWorld
          command: |
            echo 'Hello World'

workflows:
  build:
    jobs:
      - test
...
