---
version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: print HelloWorld
          command: |
            echo 'Hello World'
      - run:
          name: Save build num image tag
          command: echo ${CIRCLE_BUILD_NUM} >> /tmp/artifac-num && cat /tmp/artifac-num
      - persist_to_workspace:
          root: /
          paths:
            - tmp/artifac-num
  test:
    docker:
      - image: alpine
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: test var
          command: ls
      - run:
          name: print HelloWorld
          command: |
            echo 'Hello My Friend'

workflows:
  build-n-deploy:
    jobs:
      - build
      - test:
          requires: build
...
