---
version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: print HelloWorld
          command: |
            echo 'Hello World'
  test:
    docker:
      - image: alpine
    steps:
      - run:
          name: print HelloWorld
          command: |
            echo 'Hello My Friend'

workflows:
  build-n-deploy:
    triggers: 
      - schedule:
          cron: "38 20 * * *" 
          filters:
            branches:
              only:
                - update
    jobs:
      - build
      - test
...
